# Generated by Django 4.0.4 on 2022-09-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0008_remove_botusers_last_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='orderarchive',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
    ]
