# Generated by Django 4.0.4 on 2022-10-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0009_rename_shipping_address_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='clothes_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Доступные размеры'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image_for_items_id',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='ID картинки для товара(скопировать из бота через пробел)'),
        ),
    ]
