# Generated by Django 4.0.4 on 2022-10-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0010_items_clothes_size_alter_items_image_for_items_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sizes_for_clothes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры одежды'),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='sizes_for_clothes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры одежды'),
        ),
    ]
